import { DatabaseSync } from 'node:sqlite';
import { mkdirSync, chmodSync } from 'node:fs';
import { randomBytes, randomUUID, createHash, scrypt as scryptCallback, timingSafeEqual } from 'node:crypto';
import { promisify } from 'node:util';
const scrypt=promisify(scryptCallback);
export const STATE=process.env.FINTECH_STATE||'/var/lib/fintech-demo';
mkdirSync(STATE,{recursive:true});mkdirSync(`${STATE}/cards`,{recursive:true,mode:0o700});
const db=new DatabaseSync(`${STATE}/applications.sqlite`);chmodSync(`${STATE}/applications.sqlite`,0o600);
db.exec(`PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,name TEXT NOT NULL,email TEXT UNIQUE,password_hash TEXT,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS workspaces(id TEXT PRIMARY KEY,name TEXT NOT NULL,owner_id TEXT NOT NULL REFERENCES users(id),created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS members(workspace_id TEXT REFERENCES workspaces(id),user_id TEXT REFERENCES users(id),role TEXT NOT NULL,PRIMARY KEY(workspace_id,user_id));
CREATE TABLE IF NOT EXISTS sessions(token_hash TEXT PRIMARY KEY,user_id TEXT REFERENCES users(id),workspace_id TEXT REFERENCES workspaces(id),csrf TEXT NOT NULL,expires_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS objects(workspace_id TEXT REFERENCES workspaces(id),project TEXT NOT NULL,kind TEXT NOT NULL,id TEXT NOT NULL,data TEXT NOT NULL,created_at TEXT NOT NULL,PRIMARY KEY(workspace_id,project,kind,id));
CREATE TABLE IF NOT EXISTS events(id INTEGER PRIMARY KEY AUTOINCREMENT,workspace_id TEXT REFERENCES workspaces(id),project TEXT NOT NULL,actor_id TEXT NOT NULL,action TEXT NOT NULL,data TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS operations(workspace_id TEXT REFERENCES workspaces(id),project TEXT NOT NULL,key TEXT NOT NULL,fingerprint TEXT NOT NULL,response TEXT,PRIMARY KEY(workspace_id,project,key));
CREATE TABLE IF NOT EXISTS operation_intents(workspace_id TEXT,project TEXT,key TEXT,data TEXT NOT NULL,PRIMARY KEY(workspace_id,project,key));
CREATE TABLE IF NOT EXISTS counters(id TEXT PRIMARY KEY,value INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS invitations(code_hash TEXT PRIMARY KEY,workspace_id TEXT REFERENCES workspaces(id),role TEXT NOT NULL,created_by TEXT NOT NULL,expires_at INTEGER NOT NULL,used_by TEXT);
`);
export function error(status,message){return Object.assign(new Error(message),{status});}
export function text(value,name='Value',max=140){if(typeof value!=='string'||!value.trim()||value.length>max)throw error(400,`${name} is required (maximum ${max} characters).`);return value.trim();}
export function amount(value){const s=String(value);if(!/^\d{1,9}(\.\d{1,2})?$/.test(s))throw error(400,'Enter a positive amount with at most two decimal places.');const [a,b='']=s.split('.');const n=Number(a)*100+Number(b.padEnd(2,'0'));if(n<=0||n>100000000000)throw error(400,'Amount is outside the supported range.');return n;}
const hash=s=>createHash('sha256').update(s).digest('hex');
const now=()=>new Date().toISOString();
export async function password(value){if(typeof value!=='string'||value.length<8||value.length>128)throw error(400,'Password must contain 8–128 characters.');const salt=randomBytes(16).toString('hex');const key=await scrypt(value,salt,64);return salt+':'+key.toString('hex');}
export async function verifyPassword(value,stored){if(!stored||typeof value!=='string'||value.length>128)return false;const [salt,expected]=stored.split(':');const actual=await scrypt(value,salt,64);return timingSafeEqual(actual,Buffer.from(expected,'hex'));}
function cookie(res,token){res.setHeader('Set-Cookie',`__Secure-fintech=${token}; Path=/fintech/; HttpOnly; Secure; SameSite=Lax; Max-Age=2592000`);}
export function createSession(res,user,workspace){const token=randomBytes(32).toString('hex'),csrf=randomBytes(24).toString('hex');db.prepare('INSERT INTO sessions VALUES(?,?,?,?,?)').run(hash(token),user.id,workspace,csrf,Date.now()+2592000000);cookie(res,token);return {user,workspace,csrf};}
export function session(req,required=true){const token=(req.headers.cookie||'').split(';').map(s=>s.trim()).find(s=>s.startsWith('__Secure-fintech='))?.split('=')[1];const row=token&&db.prepare('SELECT s.*,u.name,u.email,w.name as workspace_name,m.role FROM sessions s JOIN users u ON u.id=s.user_id JOIN workspaces w ON w.id=s.workspace_id JOIN members m ON m.workspace_id=w.id AND m.user_id=u.id WHERE s.token_hash=? AND s.expires_at>?').get(hash(token),Date.now());if(!row){if(required)throw error(401,'Sign in or open a workspace to continue.');return null;}return {id:row.user_id,name:row.name,email:row.email,workspace:row.workspace_id,workspaceName:row.workspace_name,role:row.role,csrf:row.csrf,tokenHash:row.token_hash};}
export function guard(req,ctx){if(!ctx||req.headers['x-csrf-token']!==ctx.csrf)throw error(403,'Session check failed. Refresh and try again.');}
export function user(ctx){return {id:ctx.id,name:ctx.name,email:ctx.email,workspace:ctx.workspace,workspaceName:ctx.workspaceName,role:ctx.role,csrf:ctx.csrf,workspaces:db.prepare('SELECT w.id,w.name,m.role FROM workspaces w JOIN members m ON m.workspace_id=w.id WHERE m.user_id=?').all(ctx.id),members:members(ctx)};}
export function members(ctx){return db.prepare('SELECT u.id,u.name,u.email,m.role FROM members m JOIN users u ON u.id=m.user_id WHERE m.workspace_id=?').all(ctx.workspace);}
export function guest(res){const id=randomUUID(),ws=randomUUID();db.exec('BEGIN');try{db.prepare('INSERT INTO users VALUES(?,?,NULL,NULL,?)').run(id,'Workspace owner',now());db.prepare('INSERT INTO workspaces VALUES(?,?,?,?)').run(ws,'My workspace',id,now());db.prepare('INSERT INTO members VALUES(?,?,?)').run(ws,id,'OWNER');db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}return createSession(res,{id,name:'Workspace owner',email:null},ws);}
export async function register(req,res,body){const name=text(body.name,'Name',64),email=text(body.email,'Email',254).toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw error(400,'Enter a valid email address.');if(db.prepare('SELECT id FROM users WHERE email=?').get(email))throw error(409,'An account with this email already exists.');const stored=await password(body.password),ctx=session(req,false);let id,ws;if(ctx&&!ctx.email){guard(req,ctx);id=ctx.id;ws=ctx.workspace;db.prepare('UPDATE users SET name=?,email=?,password_hash=? WHERE id=?').run(name,email,stored,id);}else{const created=guest(res);id=created.user.id;ws=created.workspace;db.prepare('UPDATE users SET name=?,email=?,password_hash=? WHERE id=?').run(name,email,stored,id);}return createSession(res,{id,name,email},ws);}
export async function signin(res,body){const email=text(body.email,'Email',254).toLowerCase(),u=db.prepare('SELECT * FROM users WHERE email=?').get(email);if(!u||!await verifyPassword(body.password,u.password_hash))throw error(401,'Email or password is incorrect.');const ws=db.prepare('SELECT workspace_id FROM members WHERE user_id=? ORDER BY rowid LIMIT 1').get(u.id);return createSession(res,{id:u.id,name:u.name,email:u.email},ws.workspace_id);}
export function logout(res,ctx){db.prepare('DELETE FROM sessions WHERE token_hash=?').run(ctx.tokenHash);res.setHeader('Set-Cookie','__Secure-fintech=; Path=/fintech/; HttpOnly; Secure; SameSite=Lax; Max-Age=0');}
export function switchWorkspace(ctx,id){if(!db.prepare('SELECT 1 FROM members WHERE workspace_id=? AND user_id=?').get(id,ctx.id))throw error(403,'Workspace access denied.');db.prepare('UPDATE sessions SET workspace_id=? WHERE token_hash=?').run(id,ctx.tokenHash);}
export function invite(ctx,role){if(ctx.role!=='OWNER')throw error(403,'Only the workspace owner can invite people.');if(!['ANALYST','SUPERVISOR'].includes(role))throw error(400,'Choose an analyst or supervisor role.');if(members(ctx).length>=8)throw error(422,'A workspace supports up to eight members.');const code=randomBytes(24).toString('hex');db.prepare('INSERT INTO invitations VALUES(?,?,?,?,?,NULL)').run(hash(code),ctx.workspace,role,ctx.id,Date.now()+604800000);return {code,role};}
export function acceptInvite(ctx,code){const row=db.prepare('SELECT * FROM invitations WHERE code_hash=? AND expires_at>? AND used_by IS NULL').get(hash(text(code,'Invitation',128)),Date.now());if(!row)throw error(404,'Invitation is invalid, used, or expired.');if(!ctx.email)throw error(403,'Save your account before accepting a team invitation.');if(row.created_by===ctx.id)throw error(403,'This invitation is for a different person.');if(members({workspace:row.workspace_id}).length>=8)throw error(422,'Workspace is full.');if(db.prepare('SELECT 1 FROM members WHERE workspace_id=? AND user_id=?').get(row.workspace_id,ctx.id))throw error(409,'You already belong to this workspace.');db.exec('BEGIN');try{db.prepare('INSERT INTO members VALUES(?,?,?)').run(row.workspace_id,ctx.id,row.role);db.prepare('UPDATE invitations SET used_by=? WHERE code_hash=?').run(ctx.id,hash(code));db.prepare('UPDATE sessions SET workspace_id=? WHERE token_hash=?').run(row.workspace_id,ctx.tokenHash);db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}return {joined:true};}
export function list(ctx,project,kind){return db.prepare('SELECT id,data,created_at FROM objects WHERE workspace_id=? AND project=? AND kind=? ORDER BY created_at DESC').all(ctx.workspace,project,kind).map(o=>({id:o.id,...JSON.parse(o.data),createdAt:o.created_at}));}
export function object(ctx,project,kind,id){const row=db.prepare('SELECT data,created_at FROM objects WHERE workspace_id=? AND project=? AND kind=? AND id=?').get(ctx.workspace,project,kind,String(id));if(!row)throw error(404,'Record not found in this workspace.');return {id:String(id),...JSON.parse(row.data),createdAt:row.created_at};}
export function put(ctx,project,kind,id,data){db.prepare('INSERT INTO objects VALUES(?,?,?,?,?,?) ON CONFLICT(workspace_id,project,kind,id) DO UPDATE SET data=excluded.data').run(ctx.workspace,project,kind,String(id),JSON.stringify(data),now());return {id:String(id),...data};}
export function audit(ctx,project,action,data){db.prepare('INSERT INTO events(workspace_id,project,actor_id,action,data,created_at) VALUES(?,?,?,?,?,?)').run(ctx.workspace,project,ctx.id,action,JSON.stringify(data),now());}
export function history(ctx,project){return db.prepare('SELECT e.id,e.action,e.data,e.created_at,u.name as actor FROM events e JOIN users u ON u.id=e.actor_id WHERE e.workspace_id=? AND e.project=? ORDER BY e.id DESC LIMIT 1000').all(ctx.workspace,project).map(e=>({...e,data:JSON.parse(e.data)}));}
const queues=new Map();
export async function serialize(ctx,fn){const prior=queues.get(ctx.workspace)||Promise.resolve();let release;const next=new Promise(r=>release=r);queues.set(ctx.workspace,next);await prior;try{return await fn();}finally{release();if(queues.get(ctx.workspace)===next)queues.delete(ctx.workspace);}}
export async function once(ctx,project,key,body,fn){key=text(key,'Idempotency key',128);if(!/^[\w-]{16,128}$/.test(key))throw error(400,'Invalid idempotency key.');const fingerprint=hash(JSON.stringify(body));const row=db.prepare('SELECT * FROM operations WHERE workspace_id=? AND project=? AND key=?').get(ctx.workspace,project,key);if(row&&row.fingerprint!==fingerprint)throw error(409,'This request key was already used with different details.');if(row?.response)return JSON.parse(row.response);if(!row)db.prepare('INSERT INTO operations VALUES(?,?,?,?,NULL)').run(ctx.workspace,project,key,fingerprint);const value=await fn();db.prepare('UPDATE operations SET response=? WHERE workspace_id=? AND project=? AND key=?').run(JSON.stringify(value),ctx.workspace,project,key);return value;}

// Allocate identifiers before network writes, so a retry uses the same backend identity.
export function intent(ctx,project,key,create){const old=db.prepare('SELECT data FROM operation_intents WHERE workspace_id=? AND project=? AND key=?').get(ctx.workspace,project,key);if(old)return JSON.parse(old.data);const value=create();db.prepare('INSERT INTO operation_intents VALUES(?,?,?,?)').run(ctx.workspace,project,key,JSON.stringify(value));return value;}
export function nextId(name){return db.prepare('INSERT INTO counters VALUES(?,?) ON CONFLICT(id) DO UPDATE SET value=value+1 RETURNING value').get(name,name==='card'?1000000:Date.now()*1000).value;}
