import {App,h,button,field,select,row,form,modal,table,panel,metrics,money,badge,date,short,dl,csv,notice} from './shared.js';
const app=new App({project:'quorum-ledger',title:'Quorum Ledger',abbr:'QL',accent:'#166449',tagline:'Every balance has a history.',description:'Manage accounts, move funds, reserve balances, and reconcile transactions on a replicated ledger.',views:[['overview','Overview'],['accounts','Accounts'],['transfers','Transfers'],['holds','Holds'],['activity','Activity']]});
const active=()=>app.data.accounts.filter(a=>!a.archived);
const accountOptions=()=>active().map(a=>[a.id,`${a.name} · ${a.currency} · ${money(a.available,a.currency)}`]);
function newAccount(){const d=modal('Create account',form([field('name','Account name',{maxLength:64,placeholder:'Operating account'}),select('currency','Currency',['USD','EUR','GBP'])],'Create account',async b=>{await app.action('accounts',b,'Account created.');d.close();await app.reload();}));}
function fund(a){const d=modal('Add funds · '+a.name,notice('Credits use the development funding source. No external bank transfer is initiated.'),form([field('amount',`Amount (${a.currency})`,{type:'number',min:'.01',step:'.01',placeholder:'1000.00'}),field('reference','Reference',{placeholder:'Initial funding',maxLength:140})],'Add funds',async b=>{await app.action(`accounts/${a.id}/fund`,b,'Funds posted.');d.close();await app.reload();}));}
function transfer(hold=false){if(active().length<2){app.toast('Create two accounts before transferring funds.','error');return;}const opts=accountOptions(),d=modal(hold?'Reserve funds':'New transfer',form([select('from','From account',opts),select('to','To account',opts,opts[1][0]),field('amount','Amount',{type:'number',min:'.01',step:'.01'}),field('memo','Reference',{required:false,maxLength:140,placeholder:'Invoice, payment, or internal reference'}),hold?select('timeoutSeconds','Hold expires after',[['3600','1 hour'],['86400','1 day'],['604800','7 days'],['2592000','30 days']]):null],hold?'Reserve funds':'Post transfer',async b=>{await app.action(hold?'holds':'transfers',b,hold?'Funds reserved.':'Transfer posted.');d.close();await app.reload();}));}
function accountDetail(a){modal(a.name,dl([['Currency',a.currency],['Available',money(a.available,a.currency)],['Reserved',money(a.debitsPending,a.currency)],['Credits posted',money(a.creditsPosted,a.currency)],['Debits posted',money(a.debitsPosted,a.currency)],['Account ID',h('span',{class:'mono'},a.id)]]),h('br'),h('div',{class:'actions'},button('Add funds',()=>{document.querySelector('dialog')?.close();fund(a);}),button('Archive',async()=>{try{await app.action(`accounts/${a.id}/archive`,{},'Account archived.');document.querySelector('dialog')?.close();await app.reload();}catch(e){app.toast(e.message,'error');}},'danger')));}
function holdDetail(a){const d=modal('Hold '+short(a.id),dl([['From',a.fromName],['To',a.toName],['Reserved amount',money(a.amount,a.currency)],['Status',badge(a.status)],['Expires',date(a.expiresAt)],['Reference',a.memo||'—']]));if(a.status==='ACTIVE')d.querySelector('.dialog-body').append(h('br'),form([field('amount',`Capture amount (${a.currency})`,{type:'number',step:'.01',min:'.01',max:a.amount/100,value:(a.amount/100).toFixed(2)})],'Capture funds',async b=>{await app.action(`holds/${a.id}/capture`,b,'Hold captured; unused funds released.');d.close();await app.reload();}),h('br'),button('Release entire hold',async()=>{try{await app.action(`holds/${a.id}/void`,{},'Hold released.');d.close();await app.reload();}catch(e){app.toast(e.message,'error');}},'secondary'));}
function transactionRows(items){return items.map(t=>[date(t.createdAt),t.fromName,t.toName,money(t.amount,t.currency),badge(t.type==='void'?'RELEASED':t.status),t.memo||'—',button('Details',()=>modal('Transaction',dl([['ID',h('span',{class:'mono'},t.id)],['Type',t.type],['From',t.fromName],['To',t.toName],['Amount',money(t.amount,t.currency)],['Reference',t.memo||'—'],['Posted',date(t.createdAt)]])),'secondary small')]);}
app.renderView=(page,d)=>{
 if(page==='accounts')return [app.head('Accounts','Balances are read directly from the replicated ledger.',[button('Create account',newAccount)]),panel('',table(['Account','Currency','Available','Reserved','Status',''],d.accounts.map(a=>[a.name,a.currency,money(a.available,a.currency),money(a.debitsPending,a.currency),badge(a.archived?'ARCHIVED':'ACTIVE'),button('Open',()=>accountDetail(a),'secondary small')]),'Create an account to start managing balances.'))];
 if(page==='transfers')return [app.head('Transfers','Posted transfers, funding entries, and captured reservations.',[button('Export CSV',()=>csv('transactions.csv',['Date','From','To','Amount minor','Currency','Type','Reference','ID'],d.transactions.map(t=>[t.createdAt,t.fromName,t.toName,t.amount,t.currency,t.type,t.memo,t.id])),'secondary'),button('New transfer',()=>transfer())]),panel('',table(['When','From','To','Amount','Status','Reference',''],transactionRows(d.transactions),'Your posted transactions will appear here.'))];
 if(page==='holds')return [app.head('Holds','Reserve funds now. Capture an amount or release the reservation later.',[button('Reserve funds',()=>transfer(true))]),panel('',table(['From','To','Amount','Status','Expires',''],d.holds.map(a=>[a.fromName,a.toName,money(a.amount,a.currency),badge(a.status),date(a.expiresAt),button('Manage',()=>holdDetail(a),'secondary small')]),'No holds. Reserve funds from an active account.'))];
 if(page==='activity')return [app.head('Activity','An audit trail of workspace operations.'),app.activity()];
 const usd=d.accounts.filter(a=>a.currency==='USD'),balance=usd.reduce((n,a)=>n+a.available,0),held=usd.reduce((n,a)=>n+a.debitsPending,0);
 const days=Array.from({length:7},(_,i)=>{const day=new Date(Date.now()-(6-i)*86400000);const key=day.toISOString().slice(0,10);return {label:day.toLocaleDateString(undefined,{weekday:'short'}),amount:d.transactions.filter(t=>t.currency==='USD'&&t.createdAt.slice(0,10)===key&&t.type==='transfer').reduce((n,t)=>n+t.amount,0)};});const max=Math.max(1,...days.map(x=>x.amount));
 return [app.head('Overview','Your account balances and latest ledger activity.',[button('Refresh',()=>app.reload(),'secondary'),button('New transfer',()=>transfer())]),metrics([['Available · USD',money(balance),'Across USD accounts'],['Reserved · USD',money(held),'Funds held for future capture'],['Accounts',d.accounts.length,'USD, EUR, and GBP'],['Posted transactions',d.transactions.length,'Funding, transfers, and captures']]),h('div',{class:'columns'},panel('Recent transactions',table(['When','From','To','Amount','Status','Reference',''],transactionRows(d.transactions.slice(0,8)),'Create an account and add funds to get started.')),panel('Transfer volume · last 7 days',h('div',{class:'volume'},days.map(x=>h('div',{},h('span',{class:'bar',style:`height:${Math.max(3,x.amount/max*95)}px`,title:money(x.amount)}),x.label))),h('p',{class:'muted'},'USD amounts posted by day.'),h('div',{class:'actions'},button('Create account',newAccount,'secondary'),button('Reserve funds',()=>transfer(true),'secondary'))))];
};app.start();
