export const h=(tag,attrs={},...children)=>{const e=document.createElement(tag);for(const [k,v]of Object.entries(attrs)){if(v===null||v===undefined||v===false)continue;if(k==='class')e.className=v;else if(k.startsWith('on'))e.addEventListener(k.slice(2),v);else if(k==='text')e.textContent=v;else if(k in e&&k!=='style')e[k]=v;else e.setAttribute(k,String(v));}for(const child of children.flat(Infinity))if(child!==null&&child!==undefined&&child!==false)e.append(child instanceof Node?child:document.createTextNode(String(child)));return e;};
export const money=(n,c='USD')=>new Intl.NumberFormat('en-US',{style:'currency',currency:c}).format((Number(n)||0)/100);
export const date=s=>s?new Date(s).toLocaleString(undefined,{dateStyle:'medium',timeStyle:'short'}):'—';
export const short=s=>String(s||'').length>20?String(s).slice(0,8)+'…'+String(s).slice(-6):String(s||'—');
export const badge=s=>h('span',{class:'badge '+(['POSTED','SETTLED','ACTIVE','APPROVED','AUTHORIZED','CLOSED','ACSP'].includes(s)?'good':['OPEN','QUEUED','INVESTIGATING','PENDING','CAPTURED'].includes(s)?'warn':['DECLINED','REJECTED','CRITICAL','ESCALATED','BLOCKED','LOST','STOLEN'].includes(s)?'bad':'')},s||'—');
export const button=(label,onclick,kind='')=>h('button',{type:'button',class:'button '+kind,onclick},label);
export const field=(name,label,attrs={},help)=>h('label',{class:'field'},label,h('input',{name,required:true,...attrs}),help?h('small',{},help):null);
export const select=(name,label,options,value)=>{const s=h('select',{name,required:true},options.map(o=>h('option',{value:Array.isArray(o)?o[0]:o},Array.isArray(o)?o[1]:o)));if(value!==undefined)s.value=value;return h('label',{class:'field'},label,s);};
export const textarea=(name,label,attrs={})=>h('label',{class:'field'},label,h('textarea',{name,required:true,...attrs}));
export const row=(...items)=>h('div',{class:'form-row'},items);
export const panel=(title,...children)=>h('section',{class:'panel'},title?h('h2',{},title):null,children);
export const notice=(text,kind='')=>h('div',{class:'notice '+kind},text);
export const dl=pairs=>h('dl',{class:'dl'},pairs.map(([k,v])=>h('div',{},h('dt',{},k),h('dd',{},v))));
export const metrics=items=>h('div',{class:'stats'},items.map(([label,value,note])=>h('div',{class:'stat'},h('span',{},label),h('strong',{},value),h('small',{},note||''))));
export function form(fields,label,submit){const f=h('form',{class:'form'},fields),err=h('div',{class:'notice error hidden',role:'alert'}),b=h('button',{type:'submit',class:'button'},label);f.append(err,h('div',{class:'form-footer'},b));f.addEventListener('submit',async event=>{event.preventDefault();b.disabled=true;err.classList.add('hidden');try{await submit(Object.fromEntries(new FormData(f)));}catch(e){err.textContent=e.message;err.classList.remove('hidden');}finally{b.disabled=false;}});return f;}
export function modal(title,...children){const d=h('dialog',{},h('div',{class:'dialog-head'},h('h2',{},title),button('×',()=>d.close(),'secondary close')),h('div',{class:'dialog-body'},children));document.body.append(d);d.addEventListener('close',()=>d.remove());d.addEventListener('click',e=>{if(e.target===d)d.close();});d.showModal();return d;}
export function table(columns,rows,empty='No records yet.'){let filtered=rows,page=0,sortColumn=null,ascending=true;const body=h('tbody',{}),info=h('span',{}),prev=button('Previous',()=>{page--;render();},'secondary small'),next=button('Next',()=>{page++;render();},'secondary small');const head=h('thead',{},h('tr',{},columns.map((c,i)=>h('th',{onclick:()=>{ascending=sortColumn===i?!ascending:true;sortColumn=i;filtered.sort((a,b)=>{const a1=String(a[i] instanceof Node?a[i].textContent:a[i]),b1=String(b[i] instanceof Node?b[i].textContent:b[i]);return a1.localeCompare(b1,undefined,{numeric:true})*(ascending?1:-1);});render();},title:'Sort by '+c},c))));function render(){body.replaceChildren(...filtered.slice(page*15,page*15+15).map(values=>h('tr',{},values.map(v=>h('td',{},v)))));if(!filtered.length)body.append(h('tr',{},h('td',{colSpan:columns.length},h('div',{class:'empty'},empty))));info.textContent=filtered.length?`${page*15+1}–${Math.min((page+1)*15,filtered.length)} of ${filtered.length}`:'0 records';prev.disabled=page===0;next.disabled=(page+1)*15>=filtered.length;}const search=h('input',{type:'search',class:'search',placeholder:'Search records…','aria-label':'Search records',oninput:e=>{const q=e.target.value.toLowerCase();filtered=rows.filter(v=>v.some(c=>String(c instanceof Node?c.textContent:c).toLowerCase().includes(q)));page=0;render();}});render();return h('div',{},h('div',{class:'table-toolbar'},search),h('div',{class:'table-scroll'},h('table',{},head,body)),h('div',{class:'pager'},info,h('div',{class:'actions'},prev,next)));}
export function csv(name,headers,rows){const q=v=>'"'+String(v??'').replaceAll('"','""')+'"';download(new Blob([[headers,...rows].map(r=>r.map(q).join(',')).join('\r\n')],{type:'text/csv'}),name);}
export function download(blob,name){const url=URL.createObjectURL(blob),a=h('a',{href:url,download:name});a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export class App{
 constructor(config){Object.assign(this,config);document.documentElement.style.setProperty('--accent',this.accent);this.session=null;this.data=null;this.page=location.hash.slice(1)||this.views[0][0];this.intents=new Map();}
 async request(route,options={}){const headers={...options.headers};if(this.session)headers['X-CSRF-Token']=this.session.csrf;if(options.body!==undefined){headers['Content-Type']='application/json';options.body=JSON.stringify(options.body);}const response=await fetch(route.startsWith('/')?route:'api/'+route,{...options,headers});if(!response.ok){let message=response.status===429?'Too many requests. Wait a moment and try again.':response.status>=500?'A service is unavailable. Please try again.':'Request failed';try{message=(await response.json()).error||message;}catch{}const e=Object.assign(new Error(message),{status:response.status});if(response.status===401&&this.session){this.session=null;this.auth();}throw e;}if(options.blob)return response.blob();return response.json();}
 toast(text,kind=''){document.querySelector('.toast')?.remove();const t=h('div',{class:'toast '+kind,role:'status'},text);document.body.append(t);setTimeout(()=>t.remove(),5000);}
 async action(route,body,message){const fingerprint=JSON.stringify([route,body]);let key=this.intents.get(fingerprint);if(!key){key=crypto.randomUUID();this.intents.set(fingerprint,key);}try{const result=await this.request(route,{method:'POST',body,headers:{'Idempotency-Key':key}});this.intents.delete(fingerprint);if(message)this.toast(message);return result;}catch(e){if(e.status<500)this.intents.delete(fingerprint);throw e;}}
 async start(){try{const session=await this.request('/fintech/session');if(session.user===null){this.auth();return;}this.session=session;this.shell();await this.reload();}catch(e){this.auth();this.toast(e.message,'error');}}
 auth(mode='register'){
  document.body.replaceChildren();const story=h('section',{class:'auth-story'},h('div',{class:'wordmark'},h('div',{class:'mark'},this.abbr),h('div',{},this.title,h('div',{class:'product-label'},'Eunini · Java + Rust'))),h('h1',{},this.tagline),h('p',{},this.description),h('div',{class:'auth-links'},h('a',{href:'../',style:'color:#afc3cf'},'All applications'),h('a',{href:'https://github.com/Eunini/'+this.project,style:'color:#afc3cf',target:'_blank',rel:'noopener'},'Source code')));
  const wrap=h('div',{class:'auth-form'});const draw=()=>{const register=mode==='register';wrap.replaceChildren(h('h2',{},register?'Create your workspace':'Welcome back'),h('p',{},'Your work is saved. Sign in to continue from any device.'),h('div',{class:'auth-tabs'},h('button',{class:register?'active':'',onclick:()=>{mode='register';draw();}},'Create account'),h('button',{class:!register?'active':'',onclick:()=>{mode='signin';draw();}},'Sign in')),
  form([register?field('name','Your name',{autocomplete:'name',maxLength:64}):null,field('email','Email address',{type:'email',autocomplete:'email',maxLength:254}),field('password','Password',{type:'password',minLength:8,maxLength:128,autocomplete:register?'new-password':'current-password'})],register?'Create workspace':'Sign in',async b=>{await this.request('/fintech/'+(register?'register':'signin'),{method:'POST',body:b});await this.start();}),h('p',{},'Want to explore first? ',h('button',{class:'text-button',onclick:async()=>{try{await this.request('/fintech/guest',{method:'POST',body:{}});await this.start();}catch(e){this.toast(e.message,'error');}}},'Open a workspace')),
  h('p',{class:'muted'},'Development environment. Funds, cards, and network participants are synthetic.'));};draw();document.body.append(h('main',{class:'auth-page'},story,h('div',{class:'auth-form-wrap'},wrap)));
 }
 shell(){document.body.replaceChildren();document.documentElement.style.setProperty('--accent',this.accent);this.nav=h('nav',{class:'navigation','aria-label':'Application navigation'},this.views.map(([id,label])=>h('button',{'data-page':id,onclick:()=>this.go(id)},h('span',{class:'nav-abbr'},label.slice(0,2).toUpperCase()),label)),h('button',{'data-page':'workspace',onclick:()=>this.go('workspace')},h('span',{class:'nav-abbr'},'WS'),'Workspace'));
  const ws=h('select',{class:'workspace-switch','aria-label':'Current workspace',onchange:async e=>{try{await this.request('/fintech/workspace',{method:'POST',body:{id:e.target.value}});await this.start();}catch(err){this.toast(err.message,'error');}}},this.session.workspaces.map(w=>h('option',{value:w.id,selected:w.id===this.session.workspace},w.name+(w.role==='SUPERVISOR'?' · Supervisor':''))));
  this.content=h('main',{class:'content'});this.crumb=h('span',{class:'crumb'},this.session.workspaceName+' / '+this.title);
  document.body.append(h('div',{class:'shell'},h('aside',{class:'sidebar'},h('div',{class:'wordmark'},h('div',{class:'mark'},this.abbr),h('div',{},this.title,h('div',{class:'product-label'},'Operations workspace'))),ws,this.nav,h('div',{class:'sidebar-bottom'},h('a',{href:'../'},'All applications'),h('a',{href:'https://github.com/Eunini/'+this.project,target:'_blank',rel:'noopener'},'Source code'),h('span',{},'Development · Synthetic funds'))),h('div',{class:'frame'},h('header',{class:'topbar'},this.crumb,button(this.session.name+' · '+(this.session.email?this.session.role.toLowerCase():'Save account'),()=>this.go('workspace'),'secondary user-button')),this.content)));
  window.onhashchange=()=>{this.page=location.hash.slice(1)||this.views[0][0];this.render();};
 }
 go(id){if(location.hash==='#'+id){this.page=id;this.render();}else location.hash=id;}
 async reload(){try{const [profile,state]=await Promise.all([this.request('/fintech/session'),this.request('state')]);this.session=profile;this.data=state;this.render();}catch(e){this.content.replaceChildren(notice(e.message,'error'),button('Retry',()=>this.reload()));}}
 head(title,description,actions=[]){return h('div',{class:'page-head'},h('div',{},h('h1',{},title),h('p',{},description)),h('div',{class:'actions'},actions));}
 render(){if(!this.data)return;this.nav.querySelectorAll('button').forEach(b=>b.classList.toggle('current',b.dataset.page===this.page));if(this.page==='workspace')return this.workspace();try{const view=this.renderView(this.page,this.data);this.content.replaceChildren(...(Array.isArray(view)?view:[view]));}catch(e){this.content.replaceChildren(notice(e.message,'error'));}}
 workspace(){const s=this.session,content=[this.head('Workspace','Manage your account, team, and saved work.'),panel('Account',dl([['Name',s.name],['Email',s.email||'Not saved yet'],['Role',s.role],['Workspace',s.workspaceName]]),h('br'),button('Sign out',async()=>{await this.request('/fintech/signout',{method:'POST',body:{}});this.session=null;this.auth('signin');},'secondary'))];if(!s.email)content.push(panel('Save your workspace',form([field('name','Your name',{value:s.name,maxLength:64}),field('email','Email',{type:'email'}),field('password','Password',{type:'password',minLength:8,autocomplete:'new-password'})],'Save account',async b=>{await this.request('/fintech/register',{method:'POST',body:b});await this.start();this.go('workspace');})));
  content.push(panel('Team',table(['Name','Email','Role'],s.members.map(m=>[m.name,m.email||'Guest',badge(m.role)]))));
  if(s.role==='OWNER')content.push(panel('Invite a teammate',notice('Supervisors can review STR filing requests. The person who requests a filing cannot approve it.'),form([select('role','Role',[['ANALYST','Analyst'],['SUPERVISOR','Supervisor']])],'Create invitation',async b=>{const result=await this.request('/fintech/invite',{method:'POST',body:b});const input=h('input',{value:result.code,readOnly:true,'aria-label':'Invitation code',style:'width:100%'});modal('Invitation created',h('p',{},'Share this code with your teammate. They can sign in and accept it from their Workspace page. It expires in seven days.'),input,button('Copy code',async()=>{await navigator.clipboard.writeText(result.code);this.toast('Invitation copied.');},'secondary'));})));
  content.push(panel('Join a workspace',form([field('code','Invitation code',{maxLength:128})],'Accept invitation',async b=>{await this.request('/fintech/join',{method:'POST',body:b});await this.start();this.go('workspace');})));this.content.replaceChildren(...content);
 }
 activity(){return panel('Activity log',table(['When','Action','Actor','Reference'],this.data.activity.map(e=>[date(e.created_at),e.action,e.actor,short(e.data.id||e.data.caseId||e.data.cardId||e.data.disputeId||e.data.cycleId)])));}
}
